name: Salesforce CI/CD and AI Indexing

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce Org
        run: echo "${{ secrets.SFDX_URL }}" > sfdx_auth.txt && sf org login sfdx-url --sfdx-url-file sfdx_auth.txt --alias my-org

      - name: Deploy to Org
        run: sf project deploy start --target-org my-org

      - name: Install Python Dependencies
        run: pip install beautifulsoup4 google-generativeai pinecone-client lxml

      - name: Run Metadata Indexing Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        # THE ONLY CHANGE IS HERE:
        run: python index_metadata.py